
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export PATH=/Users/jiasi/sencha/Sencha/Cmd/3.0.2.288:$PATH

export SENCHA_CMD_3_0_0="/Users/jiasi/sencha/Sencha/Cmd/3.0.2.288"
## Tizen SDK configuration
# This is generated by Tizen SDK. Please do not modify by yourself.
# Set sdb environment path
export PATH=$PATH:/Users/jiasi/tizen-sdk/tools
## End Tizen SDK configuration
